### ISSUE TITLE
GoTop erro

### ISSUE THREAD

**Issue by dougjuliao** [GainTime/gainTime#14]
Opa eae man, nessa página tem um botão "got to top" que não funcionou aqui comigo, nessa página: 
https://gaintime.github.io/grid

só passei para dar m toque mesmo  😃

**Comment by jprodrigues70** [comment]
Opa, @dougjuliao. Obrigado! 
Você pode dar informação sobre o navegador que utilizou?

**Comment by dougjuliao** [comment]
@jprodrigues70  Opa man, então eu vi no chrome mesmo só que no pc do trampo, só que testei aqui no pc da minha casa e funcionou normal rsrs...
se quiser pode fechar a issue(eu não sei como fecha rsrs). 
Mas qualquer coisa dou outra olhada la do trabalho, tranquilo?!

**Comment by jprodrigues70** [comment]
Valeu, @dougjuliao. Eu vou fechar a issue. Obrigado.
