### ISSUE TITLE
Implementar automatizador de tarefas

### ISSUE THREAD

**Issue by vncdias** [GainTime/gainTime#4]
Seria válido um automatizador de tarefas (ex. Gulp, Grunt) para garantir a execução de tarefas e uso de dependências do projeto de forma fluida para o dev.
@jprodrigues70

**Comment by jprodrigues70** [comment]
Massa @vncdias, combinei com @Marinofull de a gente ir incrementando coisas no GainTime nos fins de semana, ainda mais com a ideia do [PLUS](https://github.com/GainTime/plus). Isso daí é uma boa.

**Comment by jprodrigues70** [comment]
Feito

**Comment by vncdias** [comment]
@jprodrigues70 dentro do prazo
